AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
    FactureResizeFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: resize/
            Handler: src/index.handler
            Runtime: nodejs16.x
            Architectures:
                - x86_64
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: "es2020"
                Sourcemap: true
                EntryPoints:
                    - src/index.ts
                External:
                    - "aws-sdk"
                    - "sharp"
                    - "aws-lambda"
