version = 1.0
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "facture-resize"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17bsk8khw41bf"
s3_prefix = "facture-resize"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["FactureResizeFunction=641490273710.dkr.ecr.ap-southeast-2.amazonaws.com/facture-resize"]
